// sw.js
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

// Precache assets generated by Vite during build
precacheAndRoute(self.__WB_MANIFEST);

// Cache navigation requests
registerRoute(
  new NavigationRoute(({ event }) => {
    return new NetworkFirst().handle({ event });
  })
);
